# Basic
title: McHuang
subtitle: A blog for the Graphics world
welcome_message: <a href="https://www.apple.com/shop/buy-iphone/iphone-x" target="_blank">Buy an iPhoneX</a>
description: Just Started
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://apple.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: ganqin
    # duoshuo:

# Social
social:
    weibo:
    github: ganqin
    twitter:
    gplus:
    mail: mike.ganqin@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
